name: Build WaterCrawl Plugin

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags (e.g., v1.0)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Dify Plugin Daemon
        run: |
          wget https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.2/dify-plugin-linux-amd64 -O /tmp/dify
          chmod +x /tmp/dify

      - name: Package the plugin
        run: |
          cd /home/runner/work/watercrawl-dify-plugin && /tmp/dify plugin package ./watercrawl-dify-plugin
          
      - name: Create Release Notes
        id: create_release_notes
        run: |
          echo "## Release Notes" > release_notes.md
          echo "" >> release_notes.md
          cat CHANGELOG.md >> release_notes.md
          echo "" >> release_notes.md

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: release_notes.md
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Must be inside `with:`

      - name: Upload .difypkg file
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/watercrawl-dify-plugin/watercrawl-dify-plugin.difypkg
          asset_name: watercrawl-dify-plugin-${{ github.ref_name }}.difypkg
          asset_content_type: application/octet-stream
